version: '2.27.0'
services:

  mysql:
    container_name: 'mysql'
    restart: always
    image: mysql:9.0.1
    ports:
      - 3306:3306
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_DATABASE: storage_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

  redis:
    container_name: 'redis'
    restart: always
    image: redis:7.2
    ports:
      - 6379:6379
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - redis:/data

  minio:
    container_name: 'minio'
    restart: always
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio:/data

  app:
    container_name: 'cloud_storage'
    restart: always
    image: nkdsnnv080/storage_image:0.0.1
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      MINIO_URL: ${MINIO_URL}
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
    depends_on:
      - mysql
      - redis
      - minio

volumes:
  mysql:
  minio:
  redis:


