version: '2.27.0'
services:

  mysql:
    container_name: 'mysql'
    restart: always
    image:
      mysql:9.0.1
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: storage_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql

  redis:
    container_name: 'redis'
    restart: always
    image: redis:7.2
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  minio:
    container_name: 'minio'
    restart: always
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: rootroot
    volumes:
      - minio:/data

volumes:
  mysql:
  minio:
  redis:


